global:
  scrape_interval:     30s # Set the scrape interval. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every x seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'node' # the hardware running prometheus itself
    static_configs:
      - targets: ['localhost:9100']
